package com.epm.UserService.util;

import com.epm.UserService.model.User;

import java.time.LocalDateTime;

public interface TestsUtil {

    String INIT_DB =
            "DROP TABLE IF EXISTS users; " +
                    "CREATE TABLE users (" +
                    "user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "user_name VARCHAR(100) NOT NULL, " +
                    "password VARCHAR(100) NOT NULL, " +
                    "first_name VARCHAR(100) NOT NULL, " +
                    "last_name VARCHAR(100) NOT NULL, " +
                    "email VARCHAR(100) NOT NULL, " +
                    "gender VARCHAR(100) NOT NULL, " +
                    "age INTEGER NOT NULL, " +
                    "created_date TIMESTAMP NOT NULL, " +
                    "updated_date TIMESTAMP NOT NULL)";

    static User createUser(String username, String password, String email, String firstName, String lastName, String gender, Integer age) {

        User user = new User();

        user.setUsername(username);
        user.setPassword(password);
        user.setEmail(email);
        user.setFirstName(firstName);
        user.setLastName(lastName);
        user.setGender(gender);
        user.setAge(age);

        LocalDateTime now = LocalDateTime.now();
        user.setCreatedDate(now);
        user.setUpdatedDate(now);

        return user;
    }
}