version: "3.8"

services:
  app:
    container_name: UserService
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=UserService